--COMBUNE ÖRNEKLERÝ

-- ACTORS VE ROLLERÝNDEKÝ KAYITLARI GETÝR
select ID_, CONCAT(NAME_ ,SURNAME) from FILM_ACTORS
UNION
SELECT ACTORS_ID, ROLE_NAME FROM ROLES;

--YAPIM ÞÝRKETÝNÝN VE FILMLERÝN TÜM KAYITLRINI GETÝRÝR
SELECT NAME_,COMPANY_ID FROM FILMS
UNION ALL
SELECT NAME_,ID_ FROM PRODUCTION_COMPANY;

--FILM TABLOSUNDA KAYDI OLMAYIP FILM_TYPES TA KAYDI OLAN FÝLM TÜRLERÝNÝ BULUNUZ.
SELECT ID_ FROM FILM_TYPES
MINUS
SELECT FILM_TYPES_ID FROM FILMS;

--GOSTERÝM YERLERINDE FILMLERIN ORTAK KAYITLARINI GETÝRÝNÝZ.
SELECT FILM_ID FROM FILMS
INTERSECT 
SELECT FILM_ID FROM SHOW_LOCATION;

