--1)FILMLERÝN ORTALAMA EN YAKIN TAMSAYIYA YUVARLAMIÞ SCORUNU BULULUNUZ
SELECT NAME_, FLOOR(AVG(IMBD_SCORE)) AS PUAN FROM FILMS
GROUP BY NAME_;

--2)Yapým þirketinin ilk 3 harfini alarak hangi filmleri yaptýðýný bulunuz
SELECT SUBSTR(p.NAME_,1,3),f.ýd_ FROM PRODUCTION_COMPANY p
INNER JOIN FILMS f ON p.ýd_ = f.company_ýd;

--3)BÝR FÝLMÝN ÝSMÝNÝ VE YAPIM ÞÝRKETÝN ÝSMÝNÝ BÝRLEÞTÝRÝNÝZ
SELECT CONCAT(F.NAME_,C.NAME_) AS FILM FROM FILMS F
JOIN PRODUCTION_COMPANY C ON F.COMPANY_ID = C.ID_;

--4)ÝSMÝ EN UZUN OLAN FÝLMÝ BULUNUZ
SELECT LENGTH(NAME_),NAME_ FROM FILMS
ORDER BY LENGTH(NAME_) DESC
FETCH FIRST ROW ONLY;

--5)ROL ÝSÝMLERÝNÝN ÝÇÝNDE A HARF BULUNAN ÝLK SIRAYI BULUNUZ
SELECT A.name_ AS ACTOR_NAME,R.role_name,INSTR(ROLE_NAME,'e')from ROLES R
JOIN fýlm_actors A on R.actors_ýd = A.ýd_
where INSTR(ROLE_NAME,'e') NOT IN 0;

--6)FÝLM TÜRLERÝ ÝÇÝN BELÝRLENEN SAYILARI SOLDAN 0 YAZARAK 3 E TAMAMLAYINIZ.
SELECT LPAD(ID_,3,'0') AS ID,TYPE_NAME FROM fýlm_types;

--7)FÝLM GÖSTERÝM YERLERÝNÝN ÝSÝMLERÝ TERSTEN YAZINIZ.
SELECT REVERSE(NAME_),NAME_ FROM show_locatýon;

--8)DIRECTOR ISIMLERINI BÜYÜK HALDE GELÝCEK ÞEKÝLDE DÜZENLEYÝNÝZ
SELECT UPPER(NAME_) FROM dýrectors;

--9)ACTORLERÝN ÝSÝMLERÝNÝN ÝLK BÜYÜK OYNADIKLARI ROLLERIN ÝSÝMLERÝ KÜÇÜK OLMASINI SAÐLAYINIZ 
--VE ACTOR ÝSÝMLERÝNE GÖRE KÜÇÜKTEN BÜYÜÐE SIRALAYINIZ.
SELECT  INITCAP(A.NAME_) AS ACTOR_NAME ,LOWER(R.ROLE_NAME)AS ROLE_NAME from ROLES R
JOIN fýlm_actors A on R.actors_ýd = A.ýd_
ORDER BY A.NAME_;

--10)BÝLET IMDB SCORE LARINI AÞAGI VE YUKARI BÝR TAMSAYIYA YUVARLAYINIZ. 
SELECT NAME_,ROUND(IMBD_SCORE,0) AS YAKIN_UST_SAYI ,TRUNC(IMBD_SCORE,0) AS YAKIN_ALT_SAYI FROM FILMS;

--11)BÝLET FÝYATINI PARA BÝRÝMÝ ÝLE GÖSTERÝNÝZ.
SELECT NAME_,TO_CHAR(TICKET_PRICE,'$9999') from fýlms;

--12)FILMIN ACTORUN BOÞ OLDUÐU ALANA ACTOR YOK YA DA VAR YAZINIZ
SELECT NVL2(NAME_,'FÝLM ÝSMÝ VAR','FÝLM ÝSMÝ YOK'),NAME_ FROM FILMS;

--13)ÝSÝM UZUNLUKLARI AYNI OLAN DEÐERLERE NULL YAZDIRINIZ
SELECT NAME_,LENGTH(NAME_)"Length Name",SURNAME,LENGTH(SURNAME)"Length Surname",
nullif(LENGTH(NAME_),LENGTH(SURNAME)) "SONUC" FROM FILM_ACTORS;

--14)ACTOR VE FILMDE ÝLK NULL OLAYAN DEÐERLERÝ YAZDIR
SELECT FILM_ID,ACTORS_ID,NAME_,FILM_TYPES_ID,COALESCE(TO_CHAR(FILM_ID), TO_CHAR(ACTORS_ID),'FILM VE ACTOR YOK')
FROM FILMS;

--15)FILM LOKASYONLARINDA HANGÝ FÝLMLERÝN OLDUÐU LÝSTESÝNÝ BULUNUZ
SELECT
    NAME_, LISTAGG(FILM_ID, ',' ) WITHIN GROUP(ORDER BY FILM_ID) AS FILM_ID 
FROM show_locatýon 
GROUP BY NAME_
ORDER BY NAME_;

























