--JOIN ÖRNEKLERÝ

--1)INNER JOIN FILM TÜRÜ,ÝSMÝ,GÖSTERÝM YERÝ,VÝZYON TARIHI,OYUNCULARINI VE ROLLERININ ÝSÝMLERÝNÝ BULUNUZ
SELECT F.NAME_ "FILM NAME",A.NAME_ "ACTORS NAME",R.ROLE_NAME "ROLE NAME",S.NAME_"LOCATION NAME",V.DATE_ "VISION DATE" FROM FILMS F
INNER JOIN SHOW_LOCATION S ON F.FILM_ID =S.fýlm_ýd
INNER JOIN výsýon_date V ON V.ýd_ =F.FILM_ID
INNER JOIN FILM_ACTORS A ON F.actors_ýd = A.ýd_
INNER JOIN ROLES R  ON A.ýd_ = R.actors_ýd;

--2) NULL OLMAYAN FILMIN ACTORLERÝNÝN ÝSÝMLERÝNÝ BULUNUZ
SELECT *  FROM fýlm_actors A
LEFT JOIN FILMS F ON A.ID_ = F.FILM_ID
WHERE F.NAME_ IS NOT NULL;

--3)BÜTÜN FÝLMLERÝ GÖSTERÝLDÝÐÝ LOKASYONLARI BULUNUZ.
SELECT *  FROM FILMS F
CROSS JOIN SHOW_LOCATION S;

--4)HANGÝ OYUNCULAR  KAÇ TANE FILM DE OYNAMIÞ
SELECT DISTINCT A.NAME_, A.SURNAME,COUNT(F.FILM_ID) "OYNADIGI FILM SAYISI"  FROM FILMS F
JOIN fýlm_actors A ON  F.FILM_ID = A.ID_
GROUP BY A.NAME_, A.SURNAME, F.NAME_;







,
