
CREATE TABLE SHOW_LOCATION(
ID_ NUMBER  PRIMARY KEY,
NAME_ VARCHAR(50),
FILM_ID NUMBER,
SESSION_ID NUMBER,

CONSTRAINT FK_FILMS FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID_)ON DELETE CASCADE,
CONSTRAINT FK_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID_)ON DELETE CASCADE
);
