
INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (1,'Marza Animation Planet ');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (2,'MARVEL');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (3,'BLACK BEAR');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (4,'BLUE SKY STUDIOS');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (5,'DC FILMS');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (6,'PRESSMAN FILM');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (7,'MICHEAL BONEROYA');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (8,'WARNES BROS PICTURE');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (9,'ECHO FILMS');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (10,'VILLAGE ROADSHOW PICTURES');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (11,'HEYDAY STUDIO');

INSERT INTO PRODUCTION_COMPANY (ID_, NAME_) VALUES (12,'PARAMOUNT PICTURES');
