
INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (1,'JEFF ','FOWLER');
--Row 2
INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (2,'Anthony','RUSSO');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (3,'Peter','HEDGES');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (4,'Troy','QUANE');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (5,'Zack','SNDYER');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (6,'Patty','JENKINS');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (7,'Mathew','BROWN');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (8,'Wezner','HERZOG');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (9,'Fahad','MUSTAFA');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (10,'Guy','RITCHE');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (11,'David','YATES');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (12,'Chris','COLUMBUS');

INSERT INTO DIRECTORS (ID_, NAME_, SURNAME) VALUES (13,'Jason','REITMAN');
