
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (1,'Animasyon');

INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (2,'Fantastik');

INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (3,'Macera');
--Row 4
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (4,'Bilim Kurgu');
--Row 5
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (5,'Romantik');
--Row 6
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (6,'Komedi');
--Row 7
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (7,'Romantik Komedi');
--Row 8
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (8,'Aksiyon');
--Row 9
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (9,'Korku');
--Row 10
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (10,'gizem');
--Row 11
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (11,'Gerilim');
--Row 12
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (12,'Dram');
--Row 13
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (13,'3D');
--Row 14
INSERT INTO FILM_TYPES (ID_, TYPE_NAME) VALUES (14,'çocuk');
