
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (1,'Kirpi Sonic',1);
--Row 2
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (2,'Dr.Robotnik',2);
--Row 3
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (3,'Tom Waschowski',3);
--Row 4
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (4,'Ajan Stone',4);
--Row 5
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (5,'SHERLOCK HOLMES',5);
--Row 6
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (6,'Tony Stark(Demir Adam)',5);
--Row 7
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (7,'Steve Rogers',6);
--Row 8
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (8,'THOR',7);
--Row 9
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (9,'HULK',8);
--Row 10
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (10,'Holly Burns-beeby',9);
--Row 11
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (11,'Ben Burns',10);
--Row 12
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (12,'Neal Beeby',11);
--Row 13
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (13,'AJAN SMITH',12);
--Row 14
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (14,'HOLLANDA',13);
--Row 15
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (15,'BATMAN',14);
--Row 16
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (16,'SUPERMAN',15);
--Row 17
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (17,'WONDER WOMAN',16);
--Row 18
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (18,'Steve Trevor',17);
--Row 19
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (19,'NATASHA ROMANOV',18);
--Row 20
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (20,'SIRINIVASA ROMANUJAN',19);
--Row 21
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (21,'G.H.HARDY',20);
--Row 22
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (22,'GERTRUDE BELL',21);
--Row 23
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (23,'HENRY CADOGAN',22);
--Row 24
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (24,'ANA',23);
--Row 25
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (25,'KENNETH',24);
--Row 26
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (26,'LOIS LANE',25);
--Row 27
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (27,'null',26);
--Row 28
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (28,'null',27);
--Row 29
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (29,'DRr.JOHN WATSON',28);
--Row 30
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (30,'HARRY POTTER',29);
--Row 31
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (31,'RON WEASLEY',30);
--Row 32
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (32,'HARMONIE GRANGER',31);
--Row 33
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (33,'ALBUS DOMBLEDORE',32);
--Row 34
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (34,'SAMUEL',33);
--Row 35
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (35,'TIMOTHEE',34);
--Row 36
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (36,'TARZAN',35);
--Row 37
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (37,'George Washington Williams',36);
--Row 38
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (38,'NEWT SCAMANDER',37);
--Row 39
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (39,'PORPENTINA GOLDSTEIN',38);
--Row 40
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (40,'RYAN BINGHAM',39);
--Row 41
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (41,'NATALIA KEENER',40);
--Row 42
INSERT INTO ROLES (ID_, ROLE_NAME, ACTORS_ID) VALUES (42,'CRAIG GREGORY',41);
