
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (9,'DOLPHIN',9,4);
--Row 10
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (10,'CINEPARK',7,5);
--Row 11
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (11,'CINEMARINA',1,6);
--Row 12
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (12,'MAYA FILM PLATOSU',10,9);
--Row 13
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (13,'SYMBOL SINEMA',1,10);
--Row 14
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (14,'CINEMAMAXIMUM',11,13);
--Row 15
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (15,'DOLPHIN',15,15);
--Row 16
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (16,'CINEPARK',19,5);
--Row 17
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (17,'CINEMARINA',23,14);
--Row 18
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (18,'MAYA FILM PLATOSU',24,19);
--Row 19
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (19,'SYMBOL SINEMA',25,18);
--Row 20
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (20,'CINEMAMAXIMUM',24,16);
--Row 21
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (21,'DOLPHIN',28,14);
--Row 22
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (22,'CINEPARK',26,16);
--Row 23
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (23,'CINEMARINA',30,13);
--Row 24
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (24,'MAYA FILM PLATOSU',34,18);
--Row 25
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (25,'SYMBOL SINEMA',35,19);
--Row 26
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (26,'CINEMAMAXIMUM',36,20);
--Row 27
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (27,'DOLPHIN',38,14);
--Row 28
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (28,'CINEPARK',32,17);
--Row 29
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (29,'CINEMARINA',3,15);
--Row 30
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (30,'MAYA FILM PLATOSU',1,13);
--Row 31
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (31,'SYMBOL SINEMA',20,16);
--Row 32
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (32,'CINEMAMAXIMUM',22,18);
--Row 33
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (33,'DOLPHIN',23,19);
--Row 34
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (34,'CINEPARK',24,2);
--Row 35
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (35,'CINEMARINA',25,5);
--Row 36
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (36,'MAYA FILM PLATOSU',26,6);
--Row 37
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (37,'SYMBOL SINEMA',27,8);
--Row 38
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (38,'CINEMAMAXIMUM',28,7);
--Row 39
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (39,'DOLPHIN',29,11);
--Row 40
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (40,'CINEPARK',31,10);
--Row 41
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (41,'CINEMARINA',36,1);
--Row 42
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (42,'MAYA FILM PLATOSU',35,4);
--Row 43
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (43,'SYMBOL SINEMA',34,15);
--Row 44
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (44,'CINEMAMAXIMUM',17,16);
--Row 45
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (45,'DOLPHIN',18,18);
--Row 46
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (46,'CINEPARK',16,19);
--Row 47
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (47,'CINEMARINA',28,13);
--Row 48
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (48,'MAYA FILM PLATOSU',23,14);
--Row 49
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (49,'CINEPARK',10,15);
--Row 50
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (50,'CINEMARINA',11,17);
--Row 51
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (51,'MAYA FILM PLATOSU',17,6);
--Row 52
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (52,'SYMBOL SINEMA',19,9);
--Row 53
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (53,'CINEMAMAXIMUM',3,8);
--Row 54
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (54,'DOLPHIN',6,7);
--Row 55
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (55,'CINEPARK',5,5);
--Row 56
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (56,'CINEMARINA',8,3);
--Row 57
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (57,'MAYA FILM PLATOSU',7,2);
--Row 58
INSERT INTO SHOW_LOCATION (ID_, NAME_, SESSION_ID, FILM_ID) VALUES (58,'CINEMAMAXIMUM',9,1);
